BEGIN TRANSACTION;

-- These are just generated recipes for testing. Do not cook them, they might be poison.
-- time is an integer, represents total time to cook in minutes
-- type is delineated by a comma
-- ingredients and instructions are delineated by a semicolon per ingredient/step

INSERT INTO recipe (name, type, ingredients, time, instructions)
VALUES ('Grilled Chicken with Rosemary', 'dinner,prep', '4 Chicken Breasts; 2 tbsp Olive Oil; 4 cloves Garlic, minced; 2 tsp Fresh Rosemary, chopped; Salt; Pepper', 30, 'Preheat the grill to medium-high heat; Season the chicken breasts with salt, pepper, minced garlic, and chopped rosemary; Drizzle olive oil over the chicken; Grill the chicken for 6-8 minutes per side or until cooked through and the internal temperature reaches 165°F (74°C); Remove from the grill and let it rest for a few minutes before serving.');

INSERT INTO recipe (name, type, ingredients, time, instructions)
VALUES ('Spaghetti Carbonara', 'dinner', '12 oz Spaghetti; 6 slices Bacon, chopped; 4 Egg Yolks; 1/2 cup Grated Parmesan Cheese; Salt; Pepper', 20, 'Cook the spaghetti according to package instructions; In a skillet, cook the chopped bacon until crispy; In a bowl, whisk together the egg yolks and grated Parmesan cheese; Drain the cooked spaghetti and immediately toss it in the skillet with the bacon and bacon fat; Remove from the heat and quickly stir in the egg yolk mixture; The residual heat will cook the eggs; Season with salt and pepper; Serve immediately.');

INSERT INTO recipe (name, type, ingredients, time, instructions)
VALUES ('Honey Glazed Roasted Vegetables', 'dinner,vegetarian', '2 Carrots, peeled and sliced; 2 Zucchinis, sliced; 1 Red Bell Pepper, sliced; 1 Yellow Bell Pepper, sliced; 1/2 Red Onion, sliced; 2 tbsp Olive Oil; 2 tbsp Honey; 2 tsp Dried Thyme; Salt; Pepper', 40, 'Preheat the oven to 400°F (200°C); In a large bowl, toss together the sliced carrots, zucchinis, red bell pepper, yellow bell pepper, and red onion with olive oil, honey, dried thyme, salt, and pepper; Spread the vegetables in a single layer on a baking sheet; Roast for 30-35 minutes or until the vegetables are tender and caramelized, stirring once halfway through; Remove from the oven and serve hot.');

INSERT INTO recipe (name, type, ingredients, time, instructions)
VALUES ('Fluffy Pancakes', 'breakfast,vegetarian', '1 1/2 cups All-Purpose Flour; 3 tbsp Sugar; 1 tsp Baking Powder; 1/2 tsp Baking Soda; 1/2 tsp Salt; 1 cup Buttermilk; 1/2 cup Milk; 2 Eggs; 2 tbsp Butter, melted; 1 tsp Vanilla Extract', 20, 'In a mixing bowl, whisk together flour, sugar, baking powder, baking soda, and salt; In a separate bowl, whisk together buttermilk, milk, eggs, melted butter, and vanilla extract; Pour the wet ingredients into the dry ingredients and stir until just combined; Preheat a non-stick pan or griddle over medium heat; Pour 1/4 cup of batter onto the pan for each pancake; Cook until bubbles form on the surface, then flip and cook the other side until golden brown; Serve hot with your favorite toppings.');

INSERT INTO recipe (name, type, ingredients, time, instructions)
VALUES ('Classic French Toast', 'breakfast', '4 slices Bread; 2 Eggs; 1/2 cup Milk; 1 tsp Vanilla Extract; 1/2 tsp Cinnamon; Butter or Oil, for cooking; Maple Syrup, for serving', 15, 'In a shallow bowl, whisk together eggs, milk, vanilla extract, and cinnamon; Dip each slice of bread into the egg mixture, allowing it to soak for a few seconds on each side; Heat a non-stick skillet or griddle over medium heat and add a small amount of butter or oil to coat the surface; Place the soaked bread slices onto the hot skillet and cook until golden brown on both sides; Repeat with the remaining slices; Serve hot with maple syrup.');

INSERT INTO recipe (name, type, ingredients, time, instructions)
VALUES ('Berry Yogurt Parfait', 'breakfast,prep,vegetarian', '1 cup Greek Yogurt; 1 cup Mixed Berries (Strawberries, Blueberries, Raspberries); 1/4 cup Granola; 1 tbsp Honey', 10, 'In a glass or bowl, layer Greek yogurt, mixed berries, granola, and honey; Repeat the layers until all the ingredients are used; Finish with a dollop of Greek yogurt, a drizzle of honey, and a sprinkle of granola on top; Serve immediately and enjoy!');

INSERT INTO recipe (name, type, ingredients, time, instructions)
VALUES ('Caprese Salad', 'lunch,vegetarian', '2 Large Tomatoes; 8 oz Fresh Mozzarella Cheese; 1/4 cup Fresh Basil Leaves; 2 tbsp Balsamic Vinegar; 2 tbsp Extra Virgin Olive Oil; Salt; Pepper', 10, 'Slice the tomatoes and mozzarella cheese into 1/4-inch thick slices; Arrange the tomato slices on a serving plate; Top each tomato slice with a slice of mozzarella cheese; Place a basil leaf on top of each cheese slice; Drizzle balsamic vinegar and olive oil over the salad; Season with salt and pepper to taste; Serve immediately.');

INSERT INTO recipe (name, type, ingredients, time, instructions)
VALUES ('Chicken Caesar Wrap', 'lunch,prep', '2 Boneless, Skinless Chicken Breasts, cooked and sliced; 4 Large Flour Tortillas; 1/2 cup Caesar Salad Dressing; 2 cups Romaine Lettuce, shredded; 1/4 cup Parmesan Cheese, grated; Salt; Pepper', 15, 'Lay out the flour tortillas on a clean surface; Spread a thin layer of Caesar salad dressing over each tortilla; Place sliced cooked chicken breast on top of the dressing; Sprinkle shredded romaine lettuce and grated Parmesan cheese over the chicken; Season with salt and pepper to taste; Roll up each tortilla tightly, tucking in the sides as you go; Slice the wraps in half diagonally; Serve immediately or wrap in foil for later.');

INSERT INTO recipe (name, type, ingredients, time, instructions)
VALUES ('Mediterranean Quinoa Salad', 'lunch,vegetarian', '1 cup Quinoa, cooked; 1 cup Cucumber, diced; 1 cup Cherry Tomatoes, halved; 1/2 cup Kalamata Olives, pitted and sliced; 1/4 cup Red Onion, finely chopped; 1/4 cup Fresh Parsley, chopped; 2 tbsp Lemon Juice; 2 tbsp Extra Virgin Olive Oil; Salt; Pepper', 20, 'In a large bowl, combine cooked quinoa, cucumber, cherry tomatoes, kalamata olives, red onion, and fresh parsley; In a small bowl, whisk together lemon juice, olive oil, salt, and pepper; Pour the dressing over the quinoa mixture and toss to combine; Adjust seasoning if needed; Serve at room temperature or chilled.');

INSERT INTO recipe (name, type, ingredients, time, instructions)
VALUES ('Guacamole', 'snack,vegetarian,vegan', '2 Avocados, ripe; 1/4 cup Red Onion, finely chopped; 1/4 cup Tomato, diced; 1 Jalapeno Pepper, seeded and minced; 2 tbsp Fresh Cilantro, chopped; 1 Lime, juiced; Salt; Pepper', 10, 'In a bowl, mash the avocados with a fork until smooth but still chunky; Stir in the red onion, tomato, jalapeno pepper, and fresh cilantro; Squeeze the lime juice over the mixture and season with salt and pepper to taste; Mix well; Serve immediately with tortilla chips or as a topping for other dishes.');

INSERT INTO recipe (name, type, ingredients, time, instructions)
VALUES ('Cheesy Garlic Breadsticks', 'snack,vegetarian', '1 package Pre-made Pizza Dough; 1/4 cup Butter, melted; 2 cloves Garlic, minced; 1/4 cup Parmesan Cheese, grated; 1/4 cup Mozzarella Cheese, shredded; 1/4 tsp Dried Oregano; 1/4 tsp Dried Basil', 25, 'Preheat the oven to the temperature indicated on the pizza dough package; Roll out the pizza dough into a rectangular shape; In a small bowl, mix together melted butter and minced garlic; Brush the garlic butter mixture evenly over the pizza dough; Sprinkle grated Parmesan cheese, shredded mozzarella cheese, dried oregano, and dried basil over the dough; Cut the dough into breadstick-sized strips; Transfer the breadsticks to a baking sheet; Bake in the preheated oven according to the package instructions or until golden brown and crispy; Remove from the oven and serve warm.');

INSERT INTO recipe (name, type, ingredients, time, instructions)
VALUES ('Fruit Yogurt Parfait', 'snack,vegetarian', '1 cup Greek Yogurt; 1 cup Mixed Fresh Fruits (such as berries, chopped apples, or sliced bananas); 1/4 cup Granola; 2 tbsp Honey', 10, 'In a glass or bowl, layer Greek yogurt, mixed fresh fruits, granola, and drizzle honey on each layer; Repeat the layers until all the ingredients are used; Finish with a sprinkle of granola on top; Serve immediately and enjoy!');

INSERT INTO recipe (name, type, ingredients, time, instructions)
VALUES ('Creamy Tomato Basil Soup', 'soup,easy,prep,vegetarian', '2 cans (14 oz each) Diced Tomatoes; 1/2 cup Onion, chopped; 2 cloves Garlic, minced; 2 tbsp Butter; 2 cups Vegetable Broth; 1 cup Heavy Cream; 1/4 cup Fresh Basil Leaves, chopped; Salt; Pepper', 30, 'In a large pot, melt the butter over medium heat; Add the chopped onion and minced garlic, and cook until softened; Add the diced tomatoes (including the juice) to the pot; Stir in the vegetable broth, heavy cream, and chopped fresh basil leaves; Season with salt and pepper to taste; Bring the mixture to a boil, then reduce the heat and let it simmer for 20 minutes, stirring occasionally; Use an immersion blender or regular blender to puree the soup until smooth; Return the soup to the pot and heat it through; Serve hot with a garnish of fresh basil leaves.');

INSERT INTO recipe (name, type, ingredients, time, instructions)
VALUES ('Chicken Noodle Soup', 'soup,easy', '2 Chicken Breasts, cooked and shredded; 4 cups Chicken Broth; 1 cup Carrots, sliced; 1 cup Celery, sliced; 1/2 cup Onion, chopped; 2 cloves Garlic, minced; 1 tsp Dried Thyme; 1 tsp Dried Parsley; 1/2 tsp Salt; 1/4 tsp Black Pepper; 1 cup Egg Noodles; Fresh Parsley, chopped (for garnish)', 45, 'In a large pot, combine the chicken broth, carrots, celery, onion, garlic, dried thyme, dried parsley, salt, and black pepper; Bring the mixture to a boil over medium heat; Reduce the heat and simmer for 20 minutes, or until the vegetables are tender; Add the shredded chicken and egg noodles to the pot; Continue simmering for an additional 10-12 minutes, or until the noodles are cooked; Remove from heat and let the soup rest for a few minutes; Serve hot, garnished with fresh chopped parsley.');

INSERT INTO recipe (name, type, ingredients, time, instructions)
VALUES ('Roasted Butternut Squash Soup', 'soup,vegan,vegetarian', '1 Butternut Squash, peeled, seeded, and cubed; 1 Onion, chopped; 2 cloves Garlic, minced; 2 tbsp Olive Oil; 4 cups Vegetable Broth; 1/2 cup Heavy Cream; 1/2 tsp Ground Cinnamon; 1/4 tsp Ground Nutmeg; Salt; Pepper', 60, 'Preheat the oven to 400°F (200°C); Place the cubed butternut squash, chopped onion, and minced garlic on a baking sheet; Drizzle with olive oil and season with salt and pepper; Toss to coat the vegetables evenly; Roast in the preheated oven for 30-35 minutes, or until the squash is tender and slightly caramelized; Remove from the oven and let cool slightly; Transfer the roasted vegetables to a blender or food processor; Add vegetable broth, heavy cream, ground cinnamon, and ground nutmeg; Blend until smooth and creamy; Pour the mixture into a pot and heat it over medium-low heat until warmed through; Season with additional salt and pepper if needed; Serve hot.');

INSERT INTO recipe (name, type, ingredients, time, instructions)
VALUES ('Quick and Easy Pasta', 'dinner,fast', '8 oz Pasta; 1/4 cup Olive Oil; 2 cloves Garlic, minced; 1/4 cup Fresh Parsley, chopped; 1/4 cup Parmesan Cheese, grated; Salt; Pepper', 15, 'Cook the pasta according to package instructions; In a large skillet, heat the olive oil over medium heat; Add the minced garlic and sauté until fragrant; Drain the cooked pasta and add it to the skillet with the garlic; Toss to coat the pasta with the garlic-infused oil; Stir in the chopped fresh parsley and grated Parmesan cheese; Season with salt and pepper to taste; Serve hot.');

INSERT INTO recipe (name, type, ingredients, time, instructions)
VALUES ('Egg Fried Rice', 'dinner,fast', '2 cups Cooked Rice, cooled; 2 Eggs, beaten; 1/2 cup Frozen Peas and Carrots, thawed; 1/4 cup Onion, chopped; 2 cloves Garlic, minced; 2 tbsp Soy Sauce; 1 tbsp Sesame Oil; Salt; Pepper', 20, 'Heat a wok or large skillet over medium heat; Add a drizzle of oil and swirl it around to coat the pan; Pour the beaten eggs into the pan and scramble them; Push the scrambled eggs to one side of the pan; Add the chopped onion and minced garlic to the other side of the pan and sauté until softened; Add the thawed peas and carrots to the pan and stir-fry for a minute; Add the cooked rice to the pan and toss everything together; Drizzle soy sauce and sesame oil over the rice; Season with salt and pepper to taste; Continue stir-frying until everything is heated through; Serve hot.');

INSERT INTO recipe (name, type, ingredients, time, instructions)
VALUES ('BBQ Chicken Quesadilla', 'dinner,fast', '2 Flour Tortillas; 1 cup Cooked Chicken, shredded; 1/2 cup BBQ Sauce; 1/2 cup Shredded Cheddar Cheese; 2 Green Onions, sliced; 1/4 cup Cilantro, chopped', 10, 'Place one tortilla on a clean surface; Spread half of the BBQ sauce evenly over the tortilla; Sprinkle half of the shredded chicken, shredded cheddar cheese, sliced green onions, and chopped cilantro over one half of the tortilla; Fold the tortilla in half to cover the filling; Repeat the same process with the second tortilla and remaining ingredients; Heat a skillet or griddle over medium heat; Place one quesadilla in the skillet and cook for 2-3 minutes on each side, or until the cheese is melted and the tortilla is crispy; Repeat with the second quesadilla; Remove from heat and let them cool for a minute; Cut each quesadilla into wedges; Serve hot with additional BBQ sauce for dipping, if desired.');


COMMIT TRANSACTION;
